<div class="container">

<!--    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a id="logout" href="#/logout">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>-->

    <div class="main">
        For test: {{currentPost.title}}
        <div class="container panel">
            <h2 class="panel-heading">Add Post</h2>
            <form  class="form" name="addForm" >
                <fieldset class="form-group">
                    <a href="#/list" class="btn btn-default">Back</a>                   
                    <button type="submit" class="btn btn-default" ng-click="resetData()">Reset</button>                    
                </fieldset>
                <div class="form-group">
                    <label for="input1" class="control-label">Title</label>
                    <input type="text" class="form-control" id="input1"  ng-model="currentPost.title" required>
                </div>

                <div class="form-group">
                    <label for="add-editor" class="control-label">Description</label>
                    <textarea class="form-control ck-editor" id="add-editor"   ng-model="currentPost.description"  required></textarea>
                </div>
                <div class="form-actions">
                    <input type="button"  ng-click="addPost()" class="btn btn-default" value="Add"/>
                </div>
            </form>
        </div>
    </div>
</div>