<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">               
                <li ng-hide="hideReg()">
                    <a id="logout" href="#/registry">Registration</a>
                </li>
                <li ng-hide="hideLogin()">
                    <a id="logout" href="#/login">Login</a>
                </li>
                <li ng-hide="hideLogout()">
                    <a id="logout" href="#/logout">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>